[project]
name = 'Dj-Util'
version = '0.0.0.dev0'

description = 'Django Utilities'
readme = {file = 'README.md', content-type = 'text/markdown', charset = 'UTF-8'}

requires-python = '>= 3.8'

license = {file = 'LICENSE'}

authors = [
  {name = 'The Vinh LUONG (LƯƠNG Thế Vinh)', email = 'TheVinhLuong@gmail.com'}
]
maintainers = [
  {name = 'The Vinh LUONG (LƯƠNG Thế Vinh)', email = 'TheVinhLuong@gmail.com'}
]

keywords = [
  'Django',

  'utilities',
  'utils',
  'util',
]

classifiers = [
  'Development Status :: 5 - Production/Stable',
  # 'Development Status :: 6 - Mature',
  'Environment :: MacOS X',
  'Environment :: Win32 (MS Windows)',
  'Framework :: Django',
  'Framework :: Django :: 4.0',
  'Intended Audience :: Developers',
  'Operating System :: MacOS',
  'Operating System :: MacOS :: MacOS X',
  'Operating System :: Microsoft',
  'Operating System :: Microsoft :: Windows',
  'Operating System :: Microsoft :: Windows :: Windows 7',
  'Operating System :: Microsoft :: Windows :: Windows 8',
  'Operating System :: Microsoft :: Windows :: Windows 8.1',
  'Operating System :: Microsoft :: Windows :: Windows 10',
  'Operating System :: OS Independent',
  'Operating System :: Other OS',
  'Operating System :: POSIX',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.8',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Topic :: Scientific/Engineering',
  'Topic :: Software Development',
  'Topic :: Software Development :: Libraries',
  'Topic :: Software Development :: Libraries :: Python Modules',
]


[project.urls]
Homepage = 'https://GitHub.com/Django-AI/Dj-Util'
Repository = 'https://GitHub.com/Django-AI/Dj-Util'
GitHub = 'https://GitHub.com/Django-AI/Dj-Util'
Documentation = 'https://Django-AI.GitHub.io/Dj-Util'


[project.dependencies]
Django = '^4.0.1'
Django-Autocomplete-Light = '^3.9.0rc5'
Django-Model-Utils = '^4.2.0'


[build-system]
requires = [
  'SetUpTools >= 60.5.0',
  'Wheel >= 0.37.1',
]
build-backend = 'setuptools.build_meta'
